import { chromium } from "playwright";
const user = process.env.SUPER_ADMIN_USER, pass = process.env.SUPER_ADMIN_PASSWORD;
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1366, height: 720 } });
await pg.goto("http://localhost:8080/");
await pg.fill('input:not([type="password"])', user);
await pg.fill('input[type="password"]', pass);
await pg.keyboard.press("Enter");
await pg.waitForTimeout(2500);
await pg.click('a:has-text("Employees"), button:has-text("Employees")');
await pg.waitForTimeout(2500);
await pg.click("tbody tr");
await pg.waitForTimeout(2200);
await pg.screenshot({ path: "C:/tmp/modal2.png" });
await b.close();
